version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fredai_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  websocket-server:
    build: ./websocket-server
    ports:
      - "3001:3001"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=fredai_db
      - RASA_SERVER_URL=http://rasa:5005
    depends_on:
      mysql:
        condition: service_healthy
      rasa:
        condition: service_started

  rasa:
    build: ./backend
    ports:
      - "5005:5005"
      - "5055:5055"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=fredai_db
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "rasa train &&
             rasa run --enable-api --cors '*' --port 5005 &
             rasa run actions --port 5055"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_WEBSOCKET_URL=ws://localhost:3001
      - REACT_APP_API_BASE_URL=http://localhost:3001
    depends_on:
      - websocket-server

volumes:
  mysql_data:
