services:
  - type: web
    name: fredai-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_WEBSOCKET_URL
        value: https://fredai-websocket.onrender.com
      - key: REACT_APP_API_URL
        value: https://fredai-websocket.onrender.com

  - type: web
    name: fredai-websocket
    env: node
    buildCommand: cd websocket-server && npm install
    startCommand: cd websocket-server && node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: fredai-postgres
          property: connectionString
      - key: EMAIL_ADDRESS
        value: jeffjackson@pbascorp.com
      - key: EMAIL_PASSWORD
        value: engr qdnu cown pdsh
      - key: GEMINI_API_KEY
        value: AIzaSyBJmhJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
      - key: IMAGE_API_KEY
        value: sk-4Q4e68yR0hlTr2bPkzE650v2Nucz50UnfNA91p9k9TnxNH50

databases:
  - name: fredai-postgres
    databaseName: fredai_db
    user: fredai_user
